#!/usr/bin/env python3
"""Generate per-tech entry_points, pyproject.toml, and Claude MCP config.

By default emits launchers for ALL .md files in ../agents/ (~250).

Use a filter to only generate a subset (so `pip install -e .` only installs
those commands; the rest never appear on your PATH):

  python3 generate.py                                  # all 250
  python3 generate.py --techs postgres redis kafka     # explicit list
  python3 generate.py --from-file my_techs.txt         # one per line
  python3 generate.py --regex 'postgres|redis|.*-cli'  # regex
  python3 generate.py --list-all                       # just print available techs

After running with a filter, re-run `pip install -e .` to apply the change.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AGENTS = ROOT / "agents"
MCP_DIR = ROOT / "mcp"
PKG = MCP_DIR / "srefix_diagnosis_mcp"


def tech_from_filename(name: str) -> str:
    n = name[:-3] if name.endswith(".md") else name
    if n.endswith("-agent"):
        n = n[: -len("-agent")]
    return n


def safe_func_name(tech: str) -> str:
    return "run_" + re.sub(r"[^A-Za-z0-9_]", "_", tech)


def all_techs() -> list[str]:
    return sorted(tech_from_filename(f.name) for f in AGENTS.glob("*.md"))


def filter_techs(techs: list[str], wanted: set[str], regex: str | None) -> list[str]:
    if not wanted and not regex:
        return techs
    pat = re.compile(regex) if regex else None
    out = [t for t in techs if t in wanted or (pat and pat.search(t))]
    missing = wanted - set(out)
    if missing:
        print(f"⚠  these techs were requested but no .md file exists: {sorted(missing)}",
              file=sys.stderr)
    return out


def write_outputs(selected: list[str], total: int) -> None:
    PKG.mkdir(parents=True, exist_ok=True)

    # Symlink agents/ inside the package
    link = PKG / "agents"
    if link.is_symlink():
        link.unlink()
    elif link.exists():
        shutil.rmtree(link)
    link.symlink_to("../../agents")

    # __init__.py
    init_lines = [
        '"""Per-tech MCP server launchers (auto-generated by generate.py)."""',
        "from .server import run",
        "",
    ]
    for t in selected:
        init_lines.append(f'def {safe_func_name(t)}() -> None: run("{t}")')
    init_lines.append("")
    (PKG / "__init__.py").write_text("\n".join(init_lines))

    # pyproject.toml
    script_lines = [
        f'"srefix-diag-{t}" = "srefix_diagnosis_mcp:{safe_func_name(t)}"' for t in selected
    ]
    pyproject = (
        "[project]\n"
        'name = "srefix-diagnosis-mcp"\n'
        'version = "0.1.0"\n'
        f'description = "MCP servers exposing diagnostic knowledge for {len(selected)} technologies"\n'
        'requires-python = ">=3.10"\n'
        'dependencies = ["mcp>=1.0.0"]\n'
        "\n"
        "[project.scripts]\n"
        + "\n".join(script_lines)
        + "\n\n"
        "[build-system]\n"
        'requires = ["setuptools>=64"]\n'
        'build-backend = "setuptools.build_meta"\n'
        "\n"
        "[tool.setuptools.packages.find]\n"
        'where = ["."]\n'
        "\n"
        "[tool.setuptools.package-data]\n"
        'srefix_diagnosis_mcp = ["agents/*.md"]\n'
    )
    (MCP_DIR / "pyproject.toml").write_text(pyproject)

    # claude_mcp_config.json
    config = {
        "mcpServers": {
            f"diag-{t}": {"command": f"srefix-diag-{t}"} for t in selected
        }
    }
    (MCP_DIR / "claude_mcp_config.json").write_text(json.dumps(config, indent=2) + "\n")

    print(f"selected:               {len(selected)} of {total} techs")
    print(f"  __init__.py:          {len(selected)} run_* functions")
    print(f"  pyproject.toml:       {len(selected)} entry_points")
    print(f"  claude_mcp_config:    {len(config['mcpServers'])} servers")
    if selected:
        sample = ", ".join(f"srefix-diag-{t}" for t in selected[:5])
        if len(selected) > 5:
            sample += ", ..."
        print(f"  commands:             {sample}")
    print()
    print("Next: run `pip install -e .` to apply.")


def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawTextHelpFormatter,
    )
    ap.add_argument("--techs", nargs="*", default=[],
                    help="space-separated tech names to include")
    ap.add_argument("--from-file", type=Path,
                    help="read tech names (one per line, # comments) from file")
    ap.add_argument("--regex",
                    help="include techs whose name matches this regex")
    ap.add_argument("--list-all", action="store_true",
                    help="list all available tech names (one per line) and exit")
    args = ap.parse_args()

    techs = all_techs()

    if args.list_all:
        for t in techs:
            print(t)
        return

    wanted: set[str] = set(args.techs)
    if args.from_file and args.from_file.exists():
        wanted.update(
            line.strip() for line in args.from_file.read_text().splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        )

    selected = filter_techs(techs, wanted, args.regex)
    if not selected:
        print("⚠  no techs selected — nothing generated.", file=sys.stderr)
        sys.exit(1)

    write_outputs(selected, total=len(techs))


if __name__ == "__main__":
    main()
